from typing import Optional, List, Dict

from pydantic import BaseModel

from backend.habitlens.weekly_graph.schemas.sorting_algorithm import WeeklyOverview


class InputWeeklyOverviewState(BaseModel):
    """State associated with the weekly overview generation process, used as input."""

    """Identifier for the user, used to fetch their data."""
    user_identifier: str = "mock_user"


class WeeklyOverviewState(InputWeeklyOverviewState):
    """State associated with the weekly overview generation process."""

    """Dataframe containing the user's weekly data, which is cleaned and ready for processing."""
    week_data: Optional[List[Dict]] = None

    """Weekly overview generated by an LLM with the user's data."""
    weekly_overview: Optional[WeeklyOverview] = None

    """Path to the CSV file containing data from the user."""
    csv_path: str
